spring.application.name=TradeNow

spring.datasource.url=jdbc:postgresql://ep-restless-firefly-atsixm9i-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_mSFnoY89VAyX&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mSFnoY89VAyX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

